import {firebaseConfig} from './firebase-config.js';
import {createCampaignClient} from './campaigns-client.js?v=0.32';
import {navigation} from './navigation.js?v=0.32';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
const $=id=>document.getElementById(id),node=(tag,text='')=>{const el=document.createElement(tag);el.textContent=text;return el;},api=createCampaignClient();
let user=null,epoch=0,cid=null,data=null,busy=false,dialog=null,timer=null;
const labels={offer:'Mida soovid reklaamida? Kirjelda toodet või teenust.',objective:'Mida soovid kampaaniaga saavutada?',audience:'Kes võiks olla sinu klient?',locations:'Kus peaksid kliendid asuma? Üks piirkond rea kohta.',monthly_budget:'Ligikaudne reklaamieelarve kuus',currency:'Eelarve valuuta',landing_page:'Millisele lehele inimesed peaksid jõudma? Kui tead.',notes:'Mida peaksime teadma või vältima?'};
const path=id=>'/clients/'+cid+'/campaigns/'+id+'/';
async function load(){if(!user||!cid)return;const capture=epoch;try{const value=await api.read(path('campaign-01')+'agency');if(capture!==epoch)return;data=value;render();$('agencyMessage').textContent='Klient '+cid+' · Taotluse esitamine ei käivita reklaami.';$('newAgency').disabled=false;}catch(e){if(capture===epoch)$('agencyMessage').textContent=e.message;}}
function render(){navigation($('navigation'),{current:'ads',clientId:cid});$('agencyReports').href='data.html?client='+cid+'&source=google_ads';const root=$('agencyCards');root.replaceChildren();
 for(const row of data.campaigns){if(!row.brief_version&&!row.agency_intake&&!row.creation)continue;const card=node('section');card.className='card';const actual=row.google_state?.result?.campaign_status;const active=!!row.creation&&actual==='ENABLED',ready=!!row.creation&&!active;
  const pending=row.agency_intake?.status==='submitted'||['unassigned','in_progress','approved','generating','awaiting_action','creating_paused'].includes(row.status);card.classList.add(active?'active':ready?'ready':pending?'submitted':'draft');
  card.append(node('p',row.label),node('h2',row.summary||'Uue kampaania soov'),node('p',active?'Reklaam on aktiivne':ready?(actual==='PAUSED'?'Reklaam on koostatud · hetkel peatatud':'Reklaam on koostatud · värske olek pole teada'):pending?'Soov on Adhallale esitatud': 'Mustand · veel esitamata'));
  if(row.agency_intake?.updated_at)card.append(node('small','Viimati muudetud '+new Date(row.agency_intake.updated_at).toLocaleDateString('et-EE')));
  const edit=node('button',pending?'Vaata või täienda soovi':'Ava kampaania soov');edit.onclick=()=>open(row);card.append(edit);
  if(row.request_id){const text={unassigned:'Ootab Adhalla ülevaatust',in_progress:'Adhalla tegeleb taotlusega',approved:'Kampaania ettevalmistamine on kinnitatud',generating:'Reklaamisisu valmib',awaiting_input:'Adhalla täpsustab lähteülesannet',awaiting_action:'Kampaania loomine on ettevalmistamisel',created_paused:'Google Adsis koostatud',rejected:'Taotlus vajab muudatusi',failed:'Adhalla kontrollib töötluse probleemi'}[row.status];if(text)card.append(node('p',text));}
  if(active){const stop=node('button','Peata reklaam');stop.onclick=async()=>{if(!confirm('Kas soovid selle kampaania reklaamid peatada?'))return;stop.disabled=true;try{await api.write(path(row.campaign_id)+'pause',{client_id:cid});$('agencyMessage').textContent='Peatamissoov on saadetud.';await load();}catch(e){$('agencyMessage').textContent=e.message;stop.disabled=false;}};card.append(stop);}root.append(card);
 }if(!root.children.length)root.append(node('p','Esita oma esimese kampaania soov.'));
}
function open(row){if(dialog)return;const capture=epoch,record=row.agency_intake;let step=0,sending=false;const values=record?.content||{...row.agency_prefill,offer:'',objective:'',audience:'',locations:'',monthly_budget:'',currency:'EUR',landing_page:'',notes:'',...row.agency_prefill};dialog=node('dialog');dialog.className='agency-wizard';dialog.setAttribute('aria-label','Kampaania soov');const modal=dialog,form=node('form'),heading=node('h2'),progress=node('p'),area=node('div'),message=node('p'),actions=node('div');actions.className='wizard-actions';message.setAttribute('role','status');const inputs={};
 for(const[key,labelText]of Object.entries(labels)){const label=node('label',labelText),input=node(key==='currency'?'select':['monthly_budget','landing_page'].includes(key)?'input':'textarea');input.value=values[key]||'';input.maxLength=key==='notes'?3000:key==='monthly_budget'?12:key==='landing_page'?500:1500;if(key==='currency'){for(const code of ['EUR','USD','GBP']){const o=node('option',code);o.value=code;input.append(o);}input.value=values[key]||'EUR';}if(key==='monthly_budget')input.inputMode='decimal';if(key==='landing_page')input.placeholder='https://';input.required=['offer','objective','locations','monthly_budget'].includes(key);label.append(input);inputs[key]={label,input};}
 const close=node('button','Sulge'),back=node('button','Tagasi'),next=node('button','Edasi'),save=node('button','Salvesta mustand'),send=node('button','Saada Adhallale');for(const b of [close,back,next,save,send])b.type='button';
 const dismiss=()=>{if(sending)return;modal.close();modal.remove();dialog=null;};close.onclick=dismiss;modal.oncancel=e=>{e.preventDefault();dismiss();};modal.onclick=e=>{if(e.target!==modal)return;const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dismiss();};
 const content=()=>Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,k==='monthly_budget'?v.input.value.trim().replace(',','.'):v.input.value.trim()]));
 function show(){area.replaceChildren();progress.textContent=(step+1)+' / 4';heading.textContent=['Sinu pakkumine ja eesmärk','Piirkond ja eelarve','Leht ja lisainfo','Vaata soov üle'][step];for(const key of [['offer','objective','audience'],['locations','monthly_budget','currency'],['landing_page','notes']][step]||[])area.append(inputs[key].label);if(step===3){const summary=node('div');summary.className='wizard-summary';for(const[k,v]of Object.entries(content()))if(v)summary.append(node('strong',labels[k]),node('p',v));area.append(summary,node('p','Adhalla täpsustab reklaamid ja tehnilised seadistused. Ligikaudne kuueelarve on planeerimiseks; see taotlus ei anna reklaami käivitamise luba.'));}back.hidden=step===0;next.hidden=step===3;send.hidden=step!==3;message.textContent='';}
 back.onclick=()=>{step--;show();};next.onclick=()=>{for(const {input}of Object.values(inputs))if(area.contains(input)&&!input.reportValidity())return;step++;show();};
 async function submit(decision){if(sending)return;if(decision==='submit'){for(const key of ['offer','objective','locations','monthly_budget'])if(!inputs[key].input.value.trim()){step=['offer','objective'].includes(key)?0:1;show();inputs[key].input.reportValidity();return;}}
  sending=true;actions.querySelectorAll('button').forEach(b=>b.disabled=true);message.textContent='Salvestan…';try{await api.write(path(row.campaign_id)+'agency',{client_id:cid,base_version:record?.version||null,decision,content:content()});if(capture!==epoch)return;sending=false;dismiss();await load();$('agencyMessage').textContent=decision==='submit'?'✓ Kampaania soov on Adhallale saadetud. Töötaja vaatab selle üle.':'✓ Mustand on salvestatud.';}catch(e){if(capture===epoch){message.textContent=e.field&&labels[e.field]?'Kontrolli välja: '+labels[e.field]:e.status===409?'Soov muutus teises aknas. Sulge ja ava värske versioon.':e.message;sending=false;actions.querySelectorAll('button').forEach(b=>b.disabled=false);}}}
 save.onclick=()=>submit('save');send.onclick=()=>submit('submit');actions.append(back,next,save,send,close);form.onsubmit=e=>e.preventDefault();form.append(progress,heading,area,message,actions);modal.append(form);document.body.append(modal);show();modal.showModal();
}
$('newAgency').onclick=async()=>{if(busy||dialog||!data)return;busy=true;$('newAgency').disabled=true;try{let row=data.campaigns.find(r=>!r.brief_version&&!r.agency_intake&&!r.request_id);if(!row){const created=await api.write('/clients/'+cid+'/campaigns',{client_id:cid,copy_from:null});row={campaign_id:created.campaign_id};}open(row);}catch(e){$('agencyMessage').textContent=e.message;}finally{busy=false;$('newAgency').disabled=false;}};
onAuthStateChanged(getAuth(initializeApp(firebaseConfig)),async current=>{const capture=++epoch;clearInterval(timer);dialog?.remove();dialog=null;user=current;cid=null;data=null;api.start(current);$('agencyCards').replaceChildren();$('newAgency').disabled=true;if(!current){$('agencyMessage').textContent='Logi portaali Google kontoga sisse.';return;}try{const experience=await api.read('/workspaces/'+encodeURIComponent(current.uid)+'/experience');if(capture!==epoch||experience.selection?.tier!=='agency')return;const connections=await api.read('/workspaces/'+encodeURIComponent(current.uid)+'/connections');if(capture!==epoch)return;cid=connections.client_id;if(!cid){$('agencyMessage').textContent='Kinnita ettevõtte info. Adhalla seob tööruumi püsikliendiga enne kampaaniatöö alustamist.';return;}await load();timer=setInterval(()=>{if(!document.hidden&&!dialog&&!busy)load();},30000);}catch(e){if(capture===epoch)$('agencyMessage').textContent=e.message;}});
