import {firebaseConfig} from './firebase-config.js';
import {createCampaignClient,fields,lines,states,help,normalizeBrief} from './campaigns-client.js?v=0.7';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
const $=id=>document.getElementById(id), client=createCampaignClient();
const route='/internal/clients/0000/';
let state=null, worker=false, dirty=false, proposalDirty=false, userEpoch=0, selected=null, timer=null, draftBase=null, saving=false;
let automationPrice=null;fetch('./plans.json',{cache:'no-cache'}).then(r=>r.json()).then(x=>{automationPrice=x.plans?.automation?.monthly_eur;if(state)renderResearch();}).catch(()=>{});
const say=text=>$('message').textContent=text;
function node(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
for(const [key,label,type]of fields){
 const wrap=node('div'), fieldLabel=node('label',label), input=node(['text','list'].includes(type)?'textarea':'input');input.id='brief-'+key;fieldLabel.htmlFor=input.id;wrap.append(fieldLabel);const hint=node('details');hint.className='field-help';hint.append(node('summary','? Selgitus'),node('p',help[key]));wrap.append(hint);
 if(type==='money'){input.inputMode='decimal';input.placeholder='Teadmata';}
 if(type==='url')input.placeholder='https://';
 input.maxLength=({objective:1500,landing_page:500,currency:3,strategy_notes:5000,constraints:3000})[key]||(type==='list'?16100:type==='money'?10:2000);
 if(type==='list')wrap.append(node('small','Üks väärtus rea kohta.'));
 wrap.append(input);if(['objective','offer','constraints','strategy_notes'].includes(key))wrap.className='wide';$('briefFields').append(wrap);
}
const bidding=node('label','Pakkumisstrateegia'), strategy=node('select');strategy.id='brief-bidding_strategy';
for(const [value,text]of [['MAXIMIZE_CLICKS','Maximize Clicks · võimalikult palju klikke'],['MANUAL_CPC','Manuaalne CPC · fikseeritud algpakkumine']]){const o=node('option',text);o.value=value;strategy.append(o);}bidding.append(strategy);$('briefFields').prepend(bidding);
const political=node('label','Kas kampaania sisaldab EL-i poliitreklaami?'), select=node('select');select.id='brief-eu_political_ads';
for(const [value,text]of [['unknown','Pole veel kinnitatud'],['no','Ei'],['yes','Jah']]){const o=node('option',text);o.value=value;select.append(o);}political.append(select);$('briefFields').append(political);
function fillBrief(brief){$('brief-bidding_strategy').value=brief.bidding_strategy||(state?.brief?'MANUAL_CPC':'MAXIMIZE_CLICKS');for(const[key,,type]of fields)$('brief-'+key).value=type==='list'?(brief[key]||[]).join('\n'):brief[key]??'';$('brief-eu_political_ads').value=brief.eu_political_ads||'unknown';}
function briefValue(){const result={schema_version:1};for(const[key,,type]of fields){const raw=$('brief-'+key).value.trim();result[key]=type==='list'?lines(raw):type==='money'?raw.replace(',','.')||null:raw;}result.eu_political_ads=$('brief-eu_political_ads').value;result.bidding_strategy=$('brief-bidding_strategy').value;return normalizeBrief(result);}
function input(label,value,tag='input'){const l=node('label',label),i=node(tag);i.value=value;l.append(i);return [l,i];}
let proposalInputs=null;
function renderProposal(record){
 $('proposalEmpty').hidden=!!record;$('proposalForm').hidden=!record;proposalInputs=null;$('proposalFields').replaceChildren();if(!record)return;
 const value=record.proposal, root=$('proposalFields'), [name,n]=input('Kampaania nimi',value.campaign_name),[why,w]=input('Põhjendus',value.rationale,'textarea');root.append(name,why);
 const groups=[];
 for(const group of value.ad_groups){const card=node('div');card.className='ad-group';const[nl,ni]=input('Reklaamirühm',group.name),[hl,hi]=input('Pealkirjad · üks rea kohta · kuni 30 märki',group.headlines.join('\n'),'textarea'),[dl,di]=input('Kirjeldused · üks rea kohta · kuni 90 märki',group.descriptions.join('\n'),'textarea');card.append(nl,hl,dl);const keywords=[];
 for(const kw of group.keywords){const row=node('div');row.className='keyword-row';const t=node('input');t.value=kw.text;t.setAttribute('aria-label','Märksõna');const s=node('select');s.setAttribute('aria-label','Vaste tüüp');for(const[v,label]of [['EXACT','Täpne'],['PHRASE','Fraas']]){const o=node('option',label);o.value=v;s.append(o);}s.value=kw.match;row.append(t,s);card.append(row);keywords.push([t,s]);}root.append(card);groups.push({ni,hi,di,keywords});}
 const[nl,neg]=input('Välistavad märksõnad · üks rea kohta',value.negative_keywords.join('\n'),'textarea');root.append(nl);
 if(value.assumptions.length){root.append(node('h3','Eeldused, mida üle vaadata'));const list=node('ul');value.assumptions.forEach(x=>list.append(node('li',x)));root.append(list);}
 proposalInputs={n,w,groups,neg,original:value};
}
function proposalValue(){const p=proposalInputs;return {...p.original,campaign_name:p.n.value.trim(),rationale:p.w.value.trim(),negative_keywords:lines(p.neg.value),ad_groups:p.groups.map(g=>({name:g.ni.value.trim(),headlines:lines(g.hi.value),descriptions:lines(g.di.value),keywords:g.keywords.map(([t,s])=>({text:t.value.trim(),match:s.value}))}))};}
function render(populate=false){
 if(!dirty){fillBrief(state.brief?.brief||state.prefill);draftBase=state.brief?.version||null;}
 if(!proposalDirty)renderProposal(state.proposal);
 $('personalPrefill').hidden=!Object.keys(state.personal_business_draft||{}).length;
 $('briefVersion').textContent=dirty?'Salvestamata muudatused':state.brief?'Salvestatud · '+state.brief.version.slice(0,8):'Veel salvestamata';
 const labels=Object.fromEntries(fields.map(([k,l])=>[k,l]));labels.bidding_strategy='Pakkumisstrateegia';labels.eu_political_ads='Poliitreklaami kinnitus';
 $('missing').textContent=!state.brief?'Täida ja salvesta lähteülesanne.':state.brief.missing_information?.length?'Enne loomise kinnitamist täida: '+state.brief.missing_information.map(x=>labels[x]||x).join(', '):'Kõik loomise põhiväljad on täidetud.';
 const source=state.context.source_status||{};
 for(const [id,key]of [['adsState','google_ads'],['gaState','ga4'],['gtmState','gtm']]){const good=source[key]==='retrieved',configured=state.connection_status?.[key],bound=good||(configured?.bound===true&&configured?.read_enabled===true),el=$(id);el.textContent=good?'✓ Ühendatud · andmed loetud':bound?'✓ Seotud · varasem kontroll':configured?.bound===false?'○ Ühendamata':'◷ Ühendus vajab kontrolli';el.closest('article').classList.toggle('connected',bound);}
 renderResearch();updateCpc();
 $('evidenceTime').textContent=state.context.generated_at?'Viimane andmelugemine: '+new Date(state.context.generated_at).toLocaleString('et-EE'):'Värske andmelugemine on ootel.';
 $('evidence').replaceChildren();for(const fact of state.context.evidence?.observed_facts||[])$('evidence').append(node('li',fact.statement+' · '+String(fact.value)));
 $('generationStatus').textContent=state.generation?'Koostamise seis: '+(states[state.generation.status]||state.generation.status):'Esita lähteülesanne Adhalla töötajale. AI koostamine algab alles pärast kinnitamist.';
 $('executionPolicy').textContent=state.action_classes?.includes('create_campaign_paused')?'Sisemine arendusõigus: lubatud on ainult kinnitatud uue Search kampaania loomine peatatud olekus. Käivitamine ja olemasolevate kampaaniate muutmine on lukus.':'AI ettepanekud on lubatud. Kampaaniate loomise õigust pole serveris lubatud.';
 let tickets=$('clientRequests');if(!tickets){tickets=node('div');tickets.id='clientRequests';$('generationStatus').after(tickets);}tickets.replaceChildren();for(const r of state.requests||[])tickets.append(node('p','Taotlus '+r.request_id.slice(0,8)+' · '+(states[r.status]||r.status)));
 $('generate').textContent='Esita Adhallale';$('generate').disabled=!state.brief||dirty;
 $('history').replaceChildren();for(const kind of ['brief','proposal']){const label=node('p',kind==='brief'?'Lähteülesande versioonid':'Ettepaneku versioonid');$('history').append(label);for(const version of state.history[kind]||[]){const b=node('button',version.slice(0,8));b.type='button';b.onclick=async()=>{try{const r=await client.read(route+kind+'/'+version);const box=$('historyDetail');box.replaceChildren(node('strong',(kind==='brief'?'Lähteülesanne':'Ettepanek')+' · '+version.slice(0,8)));const value=r[kind];for(const[k,v]of Object.entries(value)){if(k==='schema_version')continue;box.append(node('p',(labels[k]||k)+': '+(Array.isArray(v)?v.map(x=>typeof x==='string'?x:Object.values(x).flat().join(' · ')).join('\n'):v??'Teadmata')));}box.hidden=false;}catch(e){say(e.message);}};$('history').append(b);}}
}
function clearProtected(){state=null;selected=null;draftBase=null;dirty=false;proposalDirty=false;proposalInputs=null;$('product').hidden=true;$('gate').hidden=false;$('briefForm').reset();for(const id of ['proposalFields','workerSummary','historyDetail','history','evidence','clientRequests'])$(id)?.replaceChildren();$('requestReview')?.remove();$('approvalControls').hidden=true;$('researchResults').replaceChildren();}
async function refresh(populate=false){const epoch=userEpoch;try{const result=await client.read(route+'overview');if(epoch!==userEpoch)return;state=result;$('gate').hidden=true;$('product').hidden=false;render(populate);if(worker)await loadQueue();}catch(e){if(epoch===userEpoch){if([401,403].includes(e.status))clearProtected();say(e.message);if(!state)$('gateMessage').textContent=e.message;}}}
async function loadQueue(){const clients=await client.read('/worker/clients');const chooser=$('adminClient');chooser.replaceChildren();for(const item of clients){const option=node('option',item.name+' · '+item.client_id+(item.protected?' · kaitstud':''));option.value=item.client_id;option.disabled=!item.campaign_workspace;chooser.append(option);}$('clientProgress').textContent=clients.length+(clients.length===1?' klient registris. ':' klienti registris. ')+(state.brief?'Lähteülesanne salvestatud.':'Lähteülesanne veel salvestamata.')+' Puudu: '+(state.brief?.missing_information?.length??'täitmata')+'. Väliskliendi kampaaniatööruum avaneb pärast tema eraldi seostamist.';const records=await client.read('/worker/requests');const list=$('workerSummary');list.replaceChildren();if(!records.length){list.append(node('p','Ühtegi taotlust veel pole. Esita lähteülesanne kliendivaates.'));selected=null;$('approvalControls').hidden=true;$('requestReview')?.remove();return;}
 for(const r of records){const b=node('button',`Adhalla · ${r.client_id} · ${states[r.status]||r.status} · ${r.request_id.slice(0,8)}`);b.className='ticket-card';b.type='button';b.onclick=()=>review(r);list.append(b);}if(selected){const current=records.find(x=>x.request_id===selected.request_id);if(current)review(current);}}
function review(r){selected=r;$('approvalControls').hidden=false;$('approveCheck').checked=false;$('approve').disabled=true;$('approvalStatus').textContent=states[r.status]||r.status;let detail=$('requestReview');if(!detail){detail=node('div');detail.id='requestReview';$('workerSummary').after(detail);}detail.replaceChildren(node('h3','Taotlus · klient '+r.client_id),node('p','Soov: koostada ja valideerida Search kampaania ning luua see peatatud olekus. Käivitamine ei ole lubatud.'));
 const openClient=node('button','Ava selle kliendi vaade');openClient.type='button';openClient.className='secondary';openClient.onclick=()=>{if(r.client_id==='0000')mode(false);};const close=node('button','Sulge ülevaade');close.type='button';close.className='secondary';close.onclick=()=>{selected=null;detail.remove();$('approvalControls').hidden=true;};detail.append(openClient,close);
 const labels={...Object.fromEntries(fields.map(([k,l])=>[k,l])),bidding_strategy:'Pakkumisstrateegia',eu_political_ads:'EL-i poliitreklaam'};for(const[k,v]of Object.entries(r.snapshot.brief)){if(k==='schema_version')continue;detail.append(node('p',(labels[k]||k)+': '+(Array.isArray(v)?v.join(', '):v??'Teadmata')));}detail.append(node('small','Lähteülesanne '+r.snapshot.brief_version.slice(0,8)+' · Vastutav töötaja: '+(r.responsible_worker?'Määratud':'Määramata')));
 if(r.snapshot.creation_profile)detail.append(node('p','Loomiseprofiil: Google Search, '+(r.snapshot.creation_profile.bidding==='MAXIMIZE_CLICKS'?'Maximize Clicks':'manuaalne CPC')+', asukohas kohalolek. Kampaania, reklaamid ja märksõnad luuakse peatatud olekus. Sihtgrupp suunab märksõnu ja tekste; auditooriumifiltrit ei lisata. CPA/ROAS on planeerimise eesmärgid. Täiendav kohustuslik piirang peatab loomise.'));
 detail.append(node('h3','Taotlusega kaasas olev kontekst'));for(const fact of r.snapshot.context.evidence?.observed_facts||[])detail.append(node('p',fact.statement+' · '+String(fact.value)));
 for(const caution of r.snapshot.context.evidence?.cautions||[])detail.append(node('p',caution.statement));
 detail.append(node('p','Andmete aeg: '+(r.snapshot.context.generated_at?new Date(r.snapshot.context.generated_at).toLocaleString('et-EE'):'Puudub')));
 if(['unassigned','in_progress'].includes(r.status)){const claim=node('button','Võta töösse');claim.className='secondary';claim.onclick=async()=>{try{await client.write('/worker/requests/'+r.request_id+'/claim',{review_digest:r.review_digest});await loadQueue();}catch(e){say(e.message);}};detail.append(claim);}
 if(r.status==='awaiting_action')detail.append(node('p','Ettepanek on valideeritud. Järgmine samm kontrollib serveri tegevusõigust ja Google Ads loomise tingimusi.'));
 if(r.creation)detail.append(node('p','Loodud: '+r.creation.campaign_name+' · PEATATUD. Reklaame pole käivitatud.'));
 if(r.status==='reconciliation_required')detail.append(node('p','Google vastus jäi ebakindlaks. Uus loomine on lukus, kuni töötaja on tulemuse Google Adsis kontrollinud. Automaatselt uuesti ei proovita.'));
 if(['awaiting_input','failed','limited'].includes(r.status))detail.append(node('p','See katse on peatatud. Kontrolli lähteülesannet, värskeid andmeid ja kasutuspiire ning esita vajadusel uus taotlus. Automaatset korduskatset ei tehta.'));
}
function mode(value){worker=value;$('clientChooser').hidden=!worker;$('workerPanel').hidden=!worker;$('briefCard').hidden=worker;$('modeLabel').textContent=worker?'ADMINI VAADE':'KLIENDI VAADE · ADHALLA 0000';$('workerView').setAttribute('aria-pressed',String(worker));$('clientView').setAttribute('aria-pressed',String(!worker));if(worker)loadQueue().catch(e=>say(e.message));}
$('clientView').onclick=()=>mode(false);$('workerView').onclick=()=>mode(true);$('refresh').onclick=async()=>{await refresh(!dirty);say('Taotluste ja salvestuse seis uuendatud. Sinu sisestatud välju ei tühjendatud.');};
function markDirty(){document.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));dirty=true;$('generate').disabled=true;$('briefVersion').textContent='Salvestamata muudatused';updateCpc();}
$('briefForm').oninput=markDirty;$('proposalForm').oninput=()=>proposalDirty=true;
$('briefForm').onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;$('saveBrief').disabled=true;
 const value=briefValue(),signature=JSON.stringify(value);
 try{const saved=await client.write(route+'brief',{client_id:'0000',base_version:draftBase,brief:value});draftBase=saved.version;dirty=JSON.stringify(briefValue())!==signature;await refresh(!dirty);say(dirty?'Eelmine versioon salvestatud. Hilisemad sisestused vajavad veel salvestamist.':'Lähteülesanne salvestatud. Võid selle nüüd Adhallale esitada.');}
 catch(e){say(e.message);if(e.field){$('brief-'+e.field)?.setAttribute('aria-invalid','true');$('brief-'+e.field)?.focus();}if(e.status===409){await refresh(false);const box=$('conflict');box.replaceChildren(node('h3','Serveris on uuem salvestus'),node('pre',JSON.stringify(state.brief?.brief,null,2)));const use=node('button','Olen võrrelnud · salvesta minu väljad uuema versioonina');use.type='button';use.onclick=()=>{draftBase=state.brief?.version||null;box.hidden=true;$('briefForm').requestSubmit();};box.append(use);box.hidden=false;}}
 finally{saving=false;$('saveBrief').disabled=false;}};
$('prefill').onclick=()=>{const current=briefValue();for(const[k,v]of Object.entries(state.prefill)){if((current[k]===null||current[k]===''||(Array.isArray(current[k])&&!current[k].length))&&v)current[k]=v;}fillBrief(current);markDirty();$('generate').disabled=true;say('Olemasolevad äriväärtused lisatud tühjadele väljadele. Vaata üle ja salvesta.');};
$('generate').onclick=async()=>{if(dirty||!state?.brief)return;try{const r=await client.write(route+'submit',{client_id:'0000',base_version:state.brief.version});say('Taotlus '+r.request_id.slice(0,8)+' on Adhalla tööjärjekorras. Kampaaniat pole loodud.');await refresh();}catch(e){say(e.message);}};
$('proposalForm').onsubmit=async e=>{e.preventDefault();try{await client.write(route+'proposal',{client_id:'0000',base_version:state.proposal.version,proposal:proposalValue()});proposalDirty=false;await refresh();say('Muudetud ettepanek salvestatud. Muudatus ei anna loomise ega käivitamise luba.');}catch(e){say(e.message);}};
$('approveCheck').onchange=()=>{$('approve').disabled=!$('approveCheck').checked||!selected||!['unassigned','in_progress'].includes(selected.status);};
$('approve').onclick=async()=>{if(!selected||!$('approveCheck').checked)return;try{await client.write('/worker/requests/'+selected.request_id+'/approve',{review_digest:selected.review_digest});say('Täpselt see taotlus on kinnitatud. Järgmine samm on automaatne koostamine ja valideerimine.');await refresh();}catch(e){say(e.message);}};

window.addEventListener('beforeunload',e=>{if(dirty||proposalDirty){e.preventDefault();e.returnValue='';}});
function updateCpc(){const budget=Number($('brief-daily_budget').value.replace(',','.')),cap=Number($('brief-max_cpc').value.replace(',','.'));$('cpcExplanation').textContent=(strategy.value==='MAXIMIZE_CLICKS'?'Klikihinna ülempiir on valikuline. ':'Manuaalne CPC vajab algpakkumist. ')+(budget>0&&cap>0?'Päevaeelarve jagatud klikihinna ülempiiriga on ligikaudu '+(budget/cap).toFixed(1)+'. See on arvutusnäide, mitte klikkide prognoos. ':'')+'Liiga madal piir võib takistada reklaami kuvamist. Turu sobiv hinnatase sõltub konkurentsist, mitte ainult eelarvest.';}
const cpcHint=node('small');cpcHint.id='cpcExplanation';$('brief-max_cpc').after(cpcHint);
for(const key of ['keywords','competitors']){const button=node('button',key==='keywords'?'✦ Leia märksõnad Keyword Plannerist':'✦ Paku konkurente');button.id='research-'+key;button.type='button';button.className='secondary';button.onclick=async()=>{try{await client.write(route+'research',{client_id:'0000',kind:key,brief:briefValue()});say('AI uuring on tellitud. Tulemused ilmuvad siia tavaliselt järgmise 5–10 minuti jooksul. Välju ei muudeta enne sinu valikut.');await refresh(false);}catch(e){say(e.message);if(e.field){$('brief-'+e.field)?.setAttribute('aria-invalid','true');$('brief-'+e.field)?.focus();}}};$('brief-'+key).after(button);}
const negatives=node('div');negatives.className='suggested-negatives';negatives.append(node('small','Näited, mitte automaatsed välistused: '));for(const term of ['tasuta','koolitus','tööpakkumised','praktika','ise tegemine']){const b=node('button','+ '+term);b.type='button';b.className='secondary';b.onclick=()=>{const el=$('brief-negative_keywords');el.value=[...new Set([...lines(el.value),term])].join('\n');markDirty();};negatives.append(b);}$('brief-negative_keywords').after(negatives);
$('personalPrefill').onclick=()=>{const b=state.personal_business_draft||{},v=briefValue();for(const [target,source]of [['offer','offering'],['objective','objective'],['audience','customer'],['landing_page','website']])if(!v[target]&&b[source])v[target]=b[source];fillBrief(v);markDirty();say('Sinu portaali ettevõtteväljad lisati tühjadele väljadele. Kontrolli, et need kirjeldavad Adhallat (0000), ning salvesta.');};
function renderResearch(){
 const job=state.research,pending=['queued','running'].includes(job?.status);for(const key of ['keywords','competitors'])$('research-'+key).disabled=!state.research_enabled||pending;
 $('researchPlan').textContent=state.research_enabled?'AI uuringud on sisekliendi arendusõigusega avatud. Uuring ei anna reklaamide loomise luba.':'AI uuringud on Automation paketis'+(automationPrice?' · '+automationPrice+' €/kuu':'')+'. Paketiõigust kontrollib ka server.';
 const box=$('researchResults');const checked=box.dataset.job===job?.request_id?new Set([...box.querySelectorAll('input:checked')].map(el=>el.value)):new Set();box.dataset.job=job?.request_id||'';box.replaceChildren();if(!job)return;box.append(node('p','AI uuring: '+(states[job.status]||job.status)));
 if(job.status!=='completed')return;const result=job.result;box.append(node('h3',job.kind==='keywords'?'Google Keyword Planneri ideed':'AI pakutud konkurendikandidaadid · kontrollimata'),node('p',result.explanation));
 if(job.kind==='keywords')box.append(node('small','Kuni 100 ideed valitud asukohtade ja keele jaoks. Mahud ning lehe ülaosa pakkumised on ajaloolised hinnangud, mitte lubatud klikihind või garanteeritud tulemus.'));
 else box.append(node('small','Need ei ole kontrollitud 10 peamist konkurenti. Kontrolli ettevõtete olemasolu ja asjakohasust enne kasutamist.'));
 const values=job.kind==='keywords'?(result.ideas||[]):result.suggestions.map(text=>({text}));const choices=[];
 for(const idea of values){const label=node('label');label.className='research-choice';const c=node('input');c.type='checkbox';c.value=idea.text;c.checked=checked.has(idea.text);label.append(c,node('span',idea.text+(idea.avg_monthly_searches!==undefined?' · '+idea.avg_monthly_searches+' otsingut/kuu':'')));if(idea.low_top_of_page_bid_micros>0)label.append(node('small','Lehe ülaosa pakkumine: '+(idea.low_top_of_page_bid_micros/1e6).toFixed(2)+'–'+(idea.high_top_of_page_bid_micros/1e6).toFixed(2)+' '+result.currency));box.append(label);choices.push(c);}
 if(!values.length){box.append(node('p','Planner ei tagastanud ideid. Täpsusta pakkumist ja sihtimist.'));return;}
 const all=node('button','Vali kõik');all.type='button';all.className='secondary';all.onclick=()=>choices.forEach(c=>c.checked=true);
 const apply=node('button','Lisa valitud vormi');apply.type='button';apply.onclick=()=>{const field=job.kind==='keywords'?'keywords':'competitors',limit=field==='keywords'?100:20,el=$('brief-'+field);const next=[...new Set([...lines(el.value),...choices.filter(c=>c.checked).map(c=>c.value)])];if(next.length>limit){say('Valikus võib olla kuni '+limit+' rida. Vähenda valikut.');return;}el.value=next.join('\n');markDirty();say('Valik lisatud. Vaata üle ja salvesta lähteülesanne.');};box.append(all,apply);
}
onAuthStateChanged(getAuth(initializeApp(firebaseConfig)),current=>{userEpoch++;clearInterval(timer);client.start(current);clearProtected();mode(false);if(!current){$('gateMessage').textContent='Logi Google kontoga sisse portaali kaudu.';return;}refresh(true);timer=setInterval(()=>{if(!document.hidden)refresh(false);},30000);});

