const node=(tag,text='')=>{const n=document.createElement(tag);n.textContent=text;return n;};
const names={ga4:'GA4',gtm:'GTM',google_ads:'Google Ads'},states={submitted:'Uus',reviewing:'Töös',waiting_client:'Ootab klienti',resolved:'Lahendatud'};
export function connectionSupport(root,api){let epoch=0,dialog=null;
 async function load(){const capture=++epoch;try{const rows=await api.read('/worker/connection-requests');if(capture!==epoch)return;root.replaceChildren(node('h2','Ühenduste taotlused ja abipalved'));if(!rows.length)root.append(node('p','Ühendustega seotud taotlusi veel pole.'));
  for(const row of rows){const b=node('button',(row.name||'Uus tööruum')+' · '+(row.client_id||'ootab kliendinumbrit')+' · '+names[row.source]+' · '+states[row.status]);b.className='connection-support-item';b.onclick=()=>open(row);root.append(b);}
 }catch{if(capture===epoch)root.replaceChildren(node('p','Ühenduste abipalvete laadimine ei õnnestunud.'));}}
 function open(row){const capture=epoch;dialog?.remove();dialog=node('dialog');dialog.className='connection-support-dialog';const opened=dialog;const title=node('h2',names[row.source]+' · '+(row.name||row.workspace_id));dialog.setAttribute('aria-label','Ühenduse taotlus');const close=node('button','Sulge');close.onclick=()=>{dialog.remove();dialog=null;};dialog.append(title,node('p','Klient: '+(row.client_id||'veel sidumata')+' · tööruum '+row.workspace_id),node('p',row.note||'Klient esitas allika tunnused.'),node('p',Object.entries(row.resources||{}).map(([k,v])=>k+': '+v).join(' · ')),node('p','See taotlus ei anna kirjutamisõigust ega muuda ühendust. Sidumine toimub eraldi, pärast konto ja kliendi kuuluvuse kontrolli.'));
  if(row.client_id&&row.client_id!=='0000'){const link=node('a','Ava kliendi ühendamise vorm');link.href='clients.html?client='+encodeURIComponent(row.client_id);dialog.append(link);}
  const label=node('label','Vastus kliendile'),note=node('textarea');note.maxLength=2000;note.value=row.worker_note||'';note.style.width='100%';label.append(note);dialog.append(label);const status=node('p');status.setAttribute('role','status');let busy=false;
  for(const [key,text]of [['reviewing','Võta töösse'],['waiting_client','Ootan klienti'],['resolved','Märgi lahendatuks']]){const b=node('button',text);b.onclick=async()=>{if(busy)return;if(!note.value.trim()){status.textContent='Lisa kliendile selgitus.';return;}busy=true;status.textContent='Salvestan…';try{await api.write('/worker/connection-requests',{workspace_id:row.workspace_id,source:row.source,base_version:row.version,status:key,note:note.value.trim()});if(capture!==epoch||dialog!==opened)return;dialog?.remove();dialog=null;await load();}catch{status.textContent='Salvestamine ei õnnestunud. Ava taotlus uuesti, kui selle seis muutus.';}finally{busy=false;}};dialog.append(b);}
  dialog.append(status,close);document.body.append(dialog);dialog.onclick=e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom){dialog.remove();dialog=null;}};dialog.showModal();
 }
 return {load,clear(){epoch++;root.replaceChildren();dialog?.remove();dialog=null;}};
}
