import {firebaseConfig} from './firebase-config.js';
import {createCampaignClient} from './campaigns-client.js?v=0.29';
import {navigation} from './navigation.js?v=0.29';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
const api=createCampaignClient(),$=id=>document.getElementById(id),node=(tag,text='')=>{const n=document.createElement(tag);n.textContent=text;return n;};
let epoch=0,user=null,busy=false;const drafts=new Map();
const names={ga4:'Google Analytics 4',gtm:'Google Tag Manager',google_ads:'Google Ads'};
const states={connected:'✓ Ühendatud',not_connected:'○ Ühendamata',setup_incomplete:'◷ Seadistamine pooleli',needs_attention:'! Vajab tähelepanu'};
const requests={submitted:'Saadetud Adhallale',reviewing:'Adhalla vaatab üle',waiting_client:'Ootab sinu vastust',resolved:'Abipalve lahendatud'};
const fields={ga4:[['resource_id','GA4 atribuudi ID (numbrid, mitte G-…)'],['name','Atribuudi täpne nimi']],google_ads:[['resource_id','Google Adsi kliendi-ID (10 numbrit)'],['name','Konto täpne nimi']],gtm:[['account_id','GTM konto number'],['container_id','GTM konteineri number'],['public_id','Avalik konteineritunnus (GTM-…)']]};
const instructions={
 ga4:['Ava Google Analytics → Admin → Property access management. Lisa admin@adhalla.ee atribuudi Viewer ehk vaatleja rolliga. Nii saab Adhalla aruandeid ja mõõtmise seadistust lugeda; muutmisõigust pole Hindamiseks vaja.','https://support.google.com/analytics/answer/9305788'],
 gtm:['Ava Tag Manager → Admin → User Management. Lisa admin@adhalla.ee ning anna just sellele konteinerile Read ehk lugemisõigus. See lubab kontrollida märgendeid, päästikuid ja muutujaid. Edit, Approve ega Publish õigust Hindamiseks vaja ei ole. Konto ja konteineri numbrid leiad GTM-i veebiaadressist.','https://support.google.com/tagmanager/answer/6107011?hl=en'],
 google_ads:['Sisesta konto kliendi-ID ja nimi. Adhalla töötaja aitab konto siduda Adhalla haldurikontoga; Google Adsis peab konto administraator sidumistaotluse eraldi vastu võtma. Kui admin@adhalla.ee on juba konto lugeja, märgi see abipalves. Haldurikonto ligipääs võib Google’is olla laiem kui lugemine; Hindamise kasutamine ei anna Adhallale reklaamide muutmise luba.','https://support.google.com/google-ads/answer/7459601?hl=en']};
async function load(){if(!user||busy)return;const capture=epoch;$('connectionMessage').textContent='Laadin ühenduste seisu…';try{const data=await api.read('/workspaces/'+encodeURIComponent(user.uid)+'/connections');if(capture!==epoch)return;render(data);$('connectionMessage').textContent=data.client_id?'Ettevõtte kliendinumber: '+data.client_id+'. ID esitamine ei anna ligipääsu; Adhalla kontrollib seotust enne ühendamist.':'Salvesta ettevõtte info. Adhalla kinnitab sinu tööruumi püsikliendiks enne allikate ühendamist. Tunnused ja abipalved saad juba esitada.';}catch(e){if(capture===epoch)$('connectionMessage').textContent='Ühenduste seisu ei saanud laadida. Olemasolevaid ühendusi ei muudetud. Proovi uuesti.';}}
function render(data){$('sourceCards').replaceChildren();for(const row of data.sources){
 const card=node('section');card.className='card source-card';const heading=node('div');heading.className='connection-heading';const badge=node('span',states[row.status]);badge.className='connection-status '+row.status;heading.append(node('h2',names[row.source]),badge);card.append(heading);
 card.append(node('p',row.checked_at?'Viimane andmete lugemine: '+new Date(row.checked_at).toLocaleString('et-EE')+'.':'Google’i värsket lugemist pole veel kinnitatud.'));
 if(row.status==='needs_attention')card.append(node('p','Viimane kontroll ebaõnnestus või on aegunud. See ei tähenda automaatselt, et ühendus on eemaldatud. Adhalla saab lugemisõigust kontrollida.'));
 const facts=node('p');facts.className='connection-facts';facts.textContent=fields[row.source].map(([key,label])=>row.resources[key]?label+': '+row.resources[key]:'').filter(Boolean).join(' · ');card.append(facts);
 if(row.verification&&['queued','running'].includes(row.verification.status))card.append(node('p','Ühenduse kontroll on järjekorras või käib.'));
 if(row.request){const receipt=node('div');receipt.className='connection-receipt';receipt.append(node('strong',requests[row.request.status]||row.request.status),node('p',row.request.kind==='help'?row.request.note:'Esitatud tunnused: '+Object.values(row.request.resources).join(' · ')));if(row.request.worker_note)receipt.append(node('p','Adhalla: '+row.request.worker_note));card.append(receipt);}
 const guide=node('details'),summary=node('summary','Kuidas anda ligipääs?');const link=node('a','Google’i juhend');link.href=instructions[row.source][1];link.target='_blank';link.rel='noopener noreferrer';guide.append(summary,node('p',instructions[row.source][0]),link);card.append(guide);
 const draft=drafts.get(row.source);const form=node('form'),grid=node('div');grid.className='connection-resources';const inputs={};
 for(const [key,labelText]of fields[row.source]){const label=node('label',labelText),input=node('input');input.required=true;input.maxLength=key==='name'?160:30;input.value=draft?.resources?.[key]??row.request?.resources?.[key]??row.resources[key]??'';label.append(input);grid.append(label);inputs[key]=input;}
 const send=node('button','Esita tunnused Adhallale');send.type='submit';const status=node('p');status.setAttribute('role','status');form.append(grid,node('p','Tunnuste esitamine loob ülevaatustaotluse. Töötavat ühendust see ei asenda.'),send,status);card.append(form);
 const help=node('button','Küsi Adhalla abi');help.type='button';const helpForm=node('form');helpForm.className='connection-help';helpForm.hidden=true;const label=node('label','Kirjelda, millise ühendamise või andmete lugemise küsimusega abi vajad.'),note=node('textarea');note.required=true;note.maxLength=2000;note.value=draft?.note||'';helpForm.hidden=!draft?.helpOpen;label.append(note);const ask=node('button','Saada abipalve');ask.type='submit';helpForm.append(label,node('p','Ära lisa paroole ega ligipääsutokeneid.'),ask);help.onclick=()=>{helpForm.hidden=!helpForm.hidden;if(!helpForm.hidden)note.focus();};card.append(help,helpForm);
 const remember=()=>drafts.set(row.source,{resources:Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value])),note:note.value,helpOpen:!helpForm.hidden});form.oninput=remember;helpForm.oninput=remember;help.addEventListener('click',remember);
 const submit=async(kind,resources,noteText)=>{if(busy)return;const capture=epoch;busy=true;send.disabled=ask.disabled=true;status.textContent='Saadan Adhallale…';try{await api.write('/workspaces/'+encodeURIComponent(user.uid)+'/connections',{source:row.source,kind,resources,note:noteText,base_version:row.request?.version||null});if(capture!==epoch)return;drafts.delete(row.source);busy=false;await load();}catch(e){if(capture===epoch)status.textContent=e.status===409?'Taotlus on vahepeal muutunud. Uuenda seisu enne uuesti saatmist.':e.status===400?'Kontrolli tunnuseid ja täpset nime. Paroole ega võtmeid ei tohi saata.':'Saatmine ei õnnestunud. Sisestatud tekst jäi alles; proovi uuesti.';}finally{if(capture===epoch){busy=false;send.disabled=ask.disabled=false;}}};
 form.onsubmit=e=>{e.preventDefault();submit('binding',Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value.trim()])),'');};helpForm.onsubmit=e=>{e.preventDefault();submit('help',{},note.value.trim());};$('sourceCards').append(card);
}}
$('refreshConnections').onclick=load;
onAuthStateChanged(getAuth(initializeApp(firebaseConfig)),next=>{epoch++;user=next;busy=false;drafts.clear();api.start(next);$('sourceCards').replaceChildren();navigation($('navigation'),{current:'connections',worker:next?.email==='admin@adhalla.ee'});if(next)load();else $('connectionMessage').textContent='Ühenduste nägemiseks logi portaali Google kontoga sisse.';});
