const node=(tag,text)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;return el;};
export function managementReview(root,data,write,{current=()=>true,reload=()=>{}}={}){
 const captured=data.observation?.version,measurement=data.measurement_review;
 if(captured&&measurement?.goal){const section=node('details');section.append(node('summary','Kinnita mõõtmise päriskontroll'));root.append(section);
  section.append(node('p','Ühendus või tagi olemasolu ei tõesta, et päring jõudis õigesse kohta. Kinnita ainult enda tehtud testi tulemused. Kinnitus aegub seitsme päeva pärast ning lähteülesande või ühenduse muutudes.'));
  if(data.measurement_approval)section.append(node('p','Viimane kinnitus: '+new Date(data.measurement_approval.verified_at).toLocaleString('et-EE')));
  const form=node('form'),choice=node('select');choice.required=true;const blank=node('option','Vali kontrollitud põhikonversioon');blank.value='';choice.append(blank);
  for(const item of measurement.choices||[]){const option=node('option',(item.label||'Konversioon')+' · '+item.ga4_event);option.value=item.reference;choice.append(option);}const label=node('label','Eesmärk: '+measurement.goal);label.append(choice);form.append(label);
  const inputs={};for(const[key,title]of [['browser_test','Millise testi tegid brauseris ja kas sündmus jõudis õigesse Ads/GA4 sihtkohta?'],['business_outcome_test','Kuidas kontrollisid, et sündmus tähendab tegelikku soovitud äritulemust?'],['consent_test','Kuidas kontrollisid nõusoleku käitumist?']]){const l=node('label',title),input=node('textarea');input.required=true;input.maxLength=800;l.append(input);form.append(l);inputs[key]=input;}
  const confirm=node('input');confirm.type='checkbox';confirm.required=true;const confirmation=node('label');confirmation.append(confirm,document.createTextNode(' Tegin kirjeldatud kontrollid ja vastutan selle kinnituse eest.'));form.append(confirmation);const save=node('button','Salvesta mõõtmise kinnitus');save.type='submit';save.disabled=!measurement.choices?.length;form.append(save);const message=node('p');message.setAttribute('role','status');form.append(message);section.append(form);let busy=false;
  form.onsubmit=async event=>{event.preventDefault();if(busy||!form.reportValidity())return;const item=measurement.choices.find(c=>c.reference===choice.value);if(!item)return;busy=true;save.disabled=true;try{await write('attest_measurement',captured,{brief_version:measurement.brief_version,goal:measurement.goal,conversion_ref:item.reference,ga4_event:item.ga4_event,...Object.fromEntries(Object.entries(inputs).map(([key,input])=>[key,input.value.trim()]))});if(current())await reload();}catch(e){if(current()){message.textContent=e.message;busy=false;save.disabled=false;}}};
 }
 for(const experiment of (data.experiments||[]).filter(e=>e?.status==='running')){const box=node('details');box.append(node('summary','Hinda katset: '+experiment.definition.hypothesis));root.append(box);const form=node('form'),outcome=node('select');for(const[value,label]of [['inconclusive','Tõendeid pole piisavalt'],['stopped_guardrail','Peatatud ohutuspiiri tõttu'],['supported','Tulemused toetavad hüpoteesi'],['not_supported','Tulemused ei toeta hüpoteesi']]){const o=node('option',label);o.value=value;outcome.append(o);}const reason=node('textarea');reason.required=true;reason.maxLength=1000;reason.placeholder='Põhjenda tulemust loetud andmete ja katse piirangutega.';const save=node('button','Salvesta katse hinnang');save.type='submit';const msg=node('p');msg.setAttribute('role','status');form.append(outcome,reason,node('p','Hinnang ei tõenda põhjuslikku mõju. Tugev järeldus vajab katse minimaalset kestust ja tõendeid. Katse sulgemine ise ei muuda Google’i reklaame.'),save,msg);box.append(form);let busy=false;form.onsubmit=async event=>{event.preventDefault();if(busy||!form.reportValidity())return;busy=true;save.disabled=true;try{await write('close_experiment',experiment.version,{experiment_id:experiment.experiment_id,outcome:outcome.value,reason:reason.value.trim()});if(current())await reload();}catch(e){if(current()){msg.textContent=e.message;busy=false;save.disabled=false;}}};}
 if(captured&&data.observation.entities.campaign?.status==='PAUSED'){
  const box=node('details');box.append(node('summary','Kampaania käivitamise ülevaatus'),node('p','Koostab eraldi käivitamistaotluse täpse loetud kampaania kohta. Reklaame see nupp ei käivita. Järgmine kinnitamine vajab kliendi volitust, mõõtmise kontrolli, piisavat Ad Strengthi ja serveri tegevusõigust.'));
  box.append(node('p','Vali täpselt, millised peatatud reklaamirühmad, reklaamid ja märksõnad tuleb koos kampaaniaga käivitada. Varem peatatud märksõnu ei taasaktiveerita automaatselt.'));root.append(box);const children=[];
  for(const[ref,item]of Object.entries(data.observation.entities)){if(!['group','ad','keyword'].includes(item.kind)||item.status!=='PAUSED')continue;const label=node('label'),check=node('input');check.type='checkbox';check.value=ref;label.append(check,document.createTextNode(' '+({group:'Rühm',ad:'Reklaam',keyword:'Märksõna'})[item.kind]+': '+(item.name||item.text||item.headlines?.join(' · ')||'')));box.append(label,node('br'));children.push(check);}
  const button=node('button','Koosta käivitamise taotlus');button.type='button';const msg=node('p');msg.setAttribute('role','status');box.append(button,msg);
  button.onclick=async()=>{button.disabled=true;try{await write('propose',captured,{action:'activate_campaign',target:'campaign',values:{status:'ENABLED',child_refs:children.filter(c=>c.checked).map(c=>c.value)},reason:'Töötaja taotleb ülevaadatud kampaania ja täpselt valitud osade käivitamist; kinnitus ning serveri kontroll on veel vajalikud.',evidence_refs:['campaign.configuration'],experiment:null});if(current())await reload();}catch(e){if(current()){msg.textContent=e.message;button.disabled=false;}}};
 }
}
